name: selim-web-server

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml
      - name: Stop PM2
        run: pm2 stop selim_web_server
      - name: Start PM2
        run: pm2 start /home/runner/actions-runner/selim_start.sh --name selim_web_server --env selim_web_server



