name: Deploy

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push the Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
            image: konzerra/selim
            tags: latest
            registry: docker.io
            dockerfile: Dockerfile
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Deploy the Docker container on the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker pull selim
            docker stop selim || true
            docker rm selim || true
            docker run -d -p 8080:8080 --name selim selim